[package]
name = "rev_proxy"
version = "0.1.0"
edition = "2024"
default-run = "proxy"

[[bin]]
name = "proxy"
path = "src/main.rs"

[dependencies]
bytes = "1"
rand = { version = "0.10.0", features = ["thread_rng"] }
tokio = { version = "1.49.0", features = ["full"] }
